cluster_name               = "PHX-SPOC001-1"
subnet_name                = "Primary"
user                       = "admin"
password                   = "how2Demoright!"
endpoint                   = "10.38.1.9"
foundation_endpoint        = "0.0.0.0"
foundation_port            = "8000"
